### PR TITLE
fix(datagrid): prevent "manage columns" from making rows selectable

### LINKED ISSUE #475: Disabled radio buttons are getting enabled on clicking “Manage Columns” button which is at the footer of the DataGrid in the “Clarity DataGrid framework”
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug

We are using Clarity DataGrid to meet one of the functional requirements.  When we used “Hidable Columns” feature from the DataGrid along with “[clrDgSelectable]” option to enable the user to hide/show the desired columns in the DataGrid.
Used [clrDgSelectable]=”true/false” for the rows (radio buttons) based on the condition to disable/enable the row (radio buttons) and it is working fine.

But the problem surfaces when the user clicks on “Manage Columns” button (which shows up a popup to select the hide/show columns), all the disabled rows (radio buttons) are getting enabled, which is not an expected behavior, and it is defeating the objective of the required functionality.

Versions used:
    "@clr/angular": "^13.11.2",
    "@clr/icons": "^13.0.2",
    "@clr/ui": "^13.11.2",
DataGrid Enabling Radio buttons Issue7

## How to reproduce

Below is the dummy project code to reproduce the issue:

**app.module.ts**
```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from "@angular/platform-browser/animations";
import { ClarityModule } from "@clr/angular";
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
	BrowserAnimationsModule,
    ClarityModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**app.component.ts**
```
import { Component } from '@angular/core';
import {GetData1} from './datagrid.service';
import { Users } from './datagrid.model';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'datagrid-issue';
  GetData=GetData1;
  selected: Users[] = [];  
}
```

**datagrid.model**
```
export interface Users {
  id: string;
  name: string;
  creation: string;
  color: string;
  selectable: boolean;
}

export interface DataGridData{
	users: Users[];
}
```

**datagrid.service.ts**
```
import {DataGridData} from './datagrid.model';
export const GetData1: DataGridData = {
   "users":[
	{
		"id": "1234",
		"name": "User 1",
		"creation": "12-Jan-2023",
		"color": "red",
		"selectable": true	
	},
	{
		"id": "1235",
		"name": "User 2",
		"creation": "12-Jan-2023",
		"color": "red",
		"selectable": true	
	},
	{
		"id": "1236",
		"name": "User 3",
		"creation": "16-Jan-2023",
		"color": "red",
		"selectable": false	
	},
	{
		"id": "1237",
		"name": "User 4",
		"creation": "15-Jan-2023",
		"color": "red",
		"selectable": true	
	},
	{
		"id": "1238",
		"name": "User 5",
		"creation": "16-Jan-2023",
		"color": "red",
		"selectable": false	
	}
     ]
  }
```

 **app.component.html**
```
<clr-datagrid  [(clrDgSingleSelected)]="selected">
    <clr-dg-column>
<ng-container *clrDgHideableColumn="{ hidden: false }">User ID</ng-container>
   </clr-dg-column>
    <clr-dg-column>Name</clr-dg-column>
    <clr-dg-column>Creation date</clr-dg-column>
    <clr-dg-column>Favorite color</clr-dg-column>
  <clr-dg-row *clrDgItems="let user of GetData.users" [clrDgItem]="user" [clrDgSelectable]="user.selectable">
<clr-dg-cell>{{user.id}}</clr-dg-cell>
       	 <clr-dg-cell>{{user.name}}</clr-dg-cell>
        	<clr-dg-cell>{{user.creation | date}}</clr-dg-cell>
       	 <clr-dg-cell>{{user.color}}</clr-dg-cell>
    </clr-dg-row>
    <clr-dg-footer> users</clr-dg-footer>
</clr-datagrid>
```

## Expected behavior

Disabled/Enabled condition on the DataGrid rows should be retained and this behavior should not be altered even on click of “Manage Columns” button.

## Versions

**Clarity version:**

- [ ] v13.x

**Framework version:**
Angular 13, 
Angular 15

**Device:**

- Type: [Laptop]
- OS: [Windows]
- Browser [Chrome, Edge, Firefox]

## Additional notes

_Add any other notes about the problem here._

### LINKED ISSUE #503: Datagrid unselectable row allows selection if user clicks on Manage columns
Describe the bug
Datagrid disabled row allows selection if user clicks on Manage columns

How to reproduce
1. Mark any row of the datagrid as unselectable.
2. Click on Manage columns.

Expected behavior
Selection should not be allowed for the unselectable row.

Actual behavior
Selection is allowed after clicking on Manage columns.

Versions
Clarity version:
v13.13.0

Framework version:
Angular 14

Additional notes
https://stackblitz.com/edit/clarity-dark-theme-clr13-cds6-ng14-7hupuz?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

Following error is thrown in console:
zone.js:182 Uncaught Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'. Find more at https://angular.io/errors/NG0100
    at throwErrorIfNoChangesMode (core.mjs:9307:11)
    at bindingUpdated (core.mjs:14468:17)
    at pureFunction1Internal (core.mjs:22485:12)
    at Module.ɵɵpureFunction1 (core.mjs:22282:12)
    at ClrDatagridRow_ng_template_5_div_5_Template (clr-angular.mjs:15134:3531)
    at executeTemplate (core.mjs:12126:9)
    at refreshView (core.mjs:12011:13)
    at refreshEmbeddedViews (core.mjs:13039:17)
    at refreshView (core.mjs:12035:9)
    at refreshEmbeddedViews (core.mjs:13039:17)

https://user-images.githubusercontent.com/32540650/218466725-401c4cbc-2734-4b7c-a6a6-aa3644bd4076.mov

### PR DESCRIPTION
**Pull request by kevinbuhmann**
closes #475
closes #503

## PR Checklist

- [X] Tests for the changes have been added (for bug fixes / features)
- [N/A] Docs have been added / updated (for bug fixes / features)
- [N/A] If applicable, have a visual design approval

## PR Type

Bugfix

## What is the current behavior?

Clicking the "manage columns" button will make unselectable rows selectable.

Issue Number: #475 and #503

## What is the new behavior?

Clicking the "manage columns" button will not make unselectable rows selectable

## Does this PR introduce a breaking change?

No.

## Other information

This is a workaround to prevent the items `trackBy` function from being replaced when the "manage columns" button is clicked. This is not a complete solution. If there is another `ngForTrackBy` function within the datagrid in application code, it could sill replace the items `trackBy` function whether it is the row iterator or not.

### CODE REVIEW

File: projects/angular/src/data/datagrid/datagrid-items-trackby.ts [hunk 1]
```diff
@@ -16,6 +17,17 @@ export class ClrDatagridItemsTrackBy<T = any> {
 
   @Input('ngForTrackBy')
   set trackBy(value: TrackByFunction<T>) {
+    /**
+     * This is a workaround to prevent the items `trackBy` function from
+     * being replaced when the "manage columns" button is clicked. This is
+     * not a complete solution. If there is another `ngForTrackBy` function
+     * within the datagrid in application code, it could sill replace the
+     * items `trackBy` function whether it is the a row iterator or not.
```
Comment (williamernest) [inline projects/angular/src/data/datagrid/datagrid-items-trackby.ts:25]: `whether it is the a row iterator or not.` -> `whether it is the row iterator or not.`

**Review by williamernest — APPROVED** [review]

File: projects/angular/src/data/datagrid/datagrid-items-trackby.ts (hunk 1 above)
Comment (kevinbuhmann) [reply projects/angular/src/data/datagrid/datagrid-items-trackby.ts:25]: Oops. I will fix it. Thanks!

File: projects/angular/src/data/datagrid/datagrid-column-toggle.ts [hunk 2]
```diff
@@ -107,7 +108,7 @@ export class ClrDatagridColumnToggle implements OnDestroy {
 
   // Without tracking the checkboxes get rerendered on model update, which leads
   // to loss of focus after checkbox toggle.
-  trackByFn: TrackByFunction<ColumnState> = index => index;
+  readonly trackByFn = columnToggleTrackByFn;
```
Comment (williamernest) [inline projects/angular/src/data/datagrid/datagrid-column-toggle.ts:111]: Rather then ignoring the trackBy set here, could we set this trackByFn to use the same trackBy from the Items provider?

```
   constructor(
    ...
    popoverToggleService: ClrPopoverToggleService
    private items: Items,
  ) {
    if (items && items.trackBy) {
      this.trackByFn = items.trackBy;
    }
     this.subscription = popoverToggleService.openChange.subscribe(change => (this.openState = change));
  }
```

Comment (kevinbuhmann) [reply projects/angular/src/data/datagrid/datagrid-column-toggle.ts:111]: I'm confused. We don't want to use `items.trackBy` here. This `trackByFn` is for the column checkboxes in the "manage columns" popup.

Comment (williamernest) [reply projects/angular/src/data/datagrid/datagrid-column-toggle.ts:111]: Let’s sync on Monday about it. I’m also a bit confused on exactly what we’re solving here. The behavior we’re seeing is this track by function overrides the items trackby, so forcing them to be the same resolves that. This pr ignores the column trackby, which seems like the same thing as just removing the trackby from the columns.

**Review by Jinnie — APPROVED** [review]
