### PR TITLE
fix(navigation): visibility of navigation section when clicking on nav-link

### LINKED ISSUE #89: ClrNavLevel closes on .nav-link click even on large screens
**This is a bug report for the `@clr` Angular or UI versions of the design system.
For the web-component implementation of Clarity (`@cds`), visit [vmware-clarity/core](https://github.com/vmware-clarity/core).**

## Describe the bug

When using the sidenav component with the `[clr-nav-level]="2"` directive, the sidenav will close even when using a desktop browser on the larger breakpoint. This is a change that I think was introduced with this commit: https://github.com/vmware-clarity/ng-clarity/commit/af6c44ce23b47514c15dec60f1db07134cf62f1a. Prior to this, the sidenav would remain open after clicking nav items, and would only close when on small screens with the fly-out version of the menu.

The only way to get the sidenav to return then is to resize the viewport or refresh the page.

## How to reproduce

Stackblitz reproduction: https://stackblitz.com/edit/clarity-light-theme-clr12-cds5-y6zxq4?file=src%2Fapp%2Fapp.component.html

https://user-images.githubusercontent.com/6275952/164187261-d23bdb86-55fe-4f28-993c-2884a3b6d929.mp4

Set up sidenav as in the Stackblitz demo:

```html
<div class="main-container">
  <header class="header-2">
    <div class="branding">
      <a class="nav-link">
        <span class="title">Clarity</span>
      </a>
    </div>
    <div class="header-nav">
      <a class="active nav-link nav-text">Home</a>
    </div>
  </header>
  <div class="content-container">
    <nav class="sidenav" [clr-nav-level]="2">
      <ul class="nav-list">
        <a class="nav-link">Link 1</a>
        <a class="nav-link">Link 2</a>
        <a class="nav-link active">Link 3</a>
        <a class="nav-link">Link 4</a>
        <a class="nav-link">Link 5</a>
        <a class="nav-link">Link 6</a>
        <a class="nav-link">Link 7</a>
        <a class="nav-link">Link 8</a>
        <a class="nav-link active">Link 9</a>
        <a class="nav-link">Link 10</a>
      </ul>
    </nav>
    <div class="content-area">
      <h3>Content</h3>
    </div>
  </div>
</div>
```

Click any of the sidenav links and see that the sidenav closes.

## Expected behavior

It should stay open on large screens and only close for mobile breakpoints. This is how it worked up until (I think) [v12.0.14](https://github.com/vmware-clarity/ng-clarity/releases/tag/v12.0.14)

## Versions

**Clarity version:**

- [x] v12.x
- [ ] v13.x
- [ ] Other:

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 12

**Device:**

- Type: [Laptop]
- OS: [Win 10]
- Browser [Brave (Chromium)]
- Version [100]

### PR DESCRIPTION
**Pull request by bbogdanov**
Closes #89 

Signed-off-by: Bogdan Bogdanov <bbogdanov@vmware.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: projects/angular/src/layout/nav/nav-level.ts [hunk 1]
```diff
@@ -184,7 +184,7 @@ export class ClrNavLevel extends FocusTrap implements OnInit {
     while (current) {
       if (current === navHost) {
         return;
-      } else if (current.classList.contains('nav-link')) {
+      } else if (current.classList.contains('nav-link') && this._document.body.clientWidth < LARGE_BREAKPOINT) {
```
Comment (ashleyryan) [inline projects/angular/src/layout/nav/nav-level.ts:187]: This logic also exists in the [ngAfterViewInit event](https://github.com/vmware-clarity/ng-clarity/blob/f1e17c83f335029ea46b6dfdf1f0041c10e902ef/projects/angular/src/layout/nav/nav-level.ts#L112), so it could make sense to have a shared function that only closes on small screens? So the logic doesn't have to be duplicated if it needs to go somewhere else?

Comment (bbogdanov) [reply projects/angular/src/layout/nav/nav-level.ts:187]: I'm pretty sure these functions are going to change when the @cds/core v6 is released cause we'll have to adjust the code to use the new focus trap otherwise the compiler will start to complain that it can't find some classes that are provided from core (they are in >5.6.0  <6.0.0)
